---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kubefwd version
    register: kubefwd_test_output
  - name: kubefwd version
    debug:
      msg: '{{ kubefwd_test_output.stdout }}'
