---
- name: Testing andrewrothstein.kubefwd
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kubefwd version'
      ansible.builtin.command: kubefwd version
      changed_when: false
      register: kubefwd_test_output
    - name: Output from 'kubefwd version'
      ansible.builtin.debug:
        msg: '{{ kubefwd_test_output.stdout }}'
